@startuml

class User {
id
code
name
}

class LabelSet {
id
code
name
}

class Label {
id
code
name
label_set_id
}

class LabelSetItem {
id
uri
label_id
}

class LabelJob {
id
user_id
label_set_id
current_label_job_item_number
}

class LabelJobItem {
id
label_job_id
label_set_item_id
override_label_id
}

Label "1..n" -- "1" LabelSet
LabelJob "0..n" -- "1" LabelSet
LabelJob "0..n" -- "1" User
LabelJob "1" -- "0..n" LabelJobItem
LabelJobItem "0..n" -- "1" LabelSetItem

LabelSetItem "0..n" -- "1" Label
LabelJobItem "0..n" -- "0..1" Label

@enduml