@startuml

' actors

:Admin: as Admin
:User: as User
:ML: as "Machine Learning App"

' use cases

(Create User) as (create_user)
(Create Label Set) as (create_label_set)
(Create Label Set Items) as (create_items)
(Create Label Set Jobs) as (create_jobs)
(Progress Label Set Job) as (progress_job)
(Select Label Set Job Results) as (select_results)

' dependency relationships
(create_items) .up.> (create_label_set)
(create_jobs) ..> (create_user)
(create_jobs) ..> (create_items)
(progress_job) ..> (create_jobs)
(select_results) ..> (create_items)

' usage relationships

Admin ---> (create_user)
Admin ---> (create_label_set)
ML ---> (create_items)
Admin ---> (create_jobs)

User -up-> (progress_job)

ML ---> (select_results)

@enduml