@startuml

' actors

:Admin: as Admin
:User: as User
:ML: as "Machine Learning App"

' use cases

(Create Users) as (create_users)
(Create Label Sets) as (create_label_sets)
(Create Jobs) as (create_jobs)
(Assign Jobs) as (assign_jobs)
(Progress Jobs) as (progress_jobs)
(Select Job Results) as (select_job_results)

' dependency relationships

(create_jobs) .up.> (create_label_sets) : requires
(assign_jobs) ..> (create_users) : requires
(assign_jobs) ..> (create_jobs) : requires
(progress_jobs) ..> (assign_jobs) : requires
(select_job_results) ..> (create_jobs) : requires

' usage relationships

Admin ---> (create_users)
Admin ---> (create_label_sets)
ML ---> (create_jobs)
Admin ---> (assign_jobs)
User -up-> (progress_jobs)
ML ---> (select_job_results)

@enduml